from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

from simulator.config import SimulatorConfig, load_config
from simulator.fabtwin import GENERATOR_VERSION, SCHEMA_VERSION, FabTwinSimulator, canonical_hash


def build(seed: int, profile: str = "test") -> tuple[list[dict[str, Any]], dict[str, Any]]:
    """Backward-compatible M0 entry point used by foundation tests."""
    result = FabTwinSimulator(load_config(profile), seed).generate()
    return result.events, result.ground_truth


def _sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _data_card(config: SimulatorConfig, seed: int) -> str:
    return f"""# FabTwin-Sim Data Card\n\n## Classification\n\n- **Synthetic:** all process, sensor, alarm, maintenance and inspection events generated by this artifact.\n- **Evaluation-only:** `ground_truth.json`; operational services must never import or serve it.\n- **Real public data:** none is embedded in this artifact. SECOM/WM-811K/AI4I are reality anchors only.\n- **Inferred:** none at M1; detection/RCA outputs are produced in later milestones.\n\n## Reproducibility\n\n- seed: `{seed}`\n- profile: `{config.profile}`\n- config version: `{config.version}`\n- generator version: `{GENERATOR_VERSION}`\n- schema version: `{SCHEMA_VERSION}`\n\n## Mechanisms\n\nThe generator combines recipe baseline, product effect, chamber random intercept, tool aging, AR(1) process noise, shared sensor covariance, measurement noise, gradual drift and abrupt shift. F1–F4 are physical synthetic faults; F5 is sensor-only calibration bias; F6 is delivery/data-quality only.\n\n## Limitations / Not claimed\n\nThis is not Samsung or any real fab data. Anonymous SECOM features are not assigned fabricated process meanings. Synthetic inspection patterns are not claimed to have real lineage to WM-811K. The model is intentionally compact and designed for deterministic architecture/evaluation experiments, not process-physics fidelity.\n"""


def write_artifacts(output: Path, seed: int, config: SimulatorConfig) -> dict[str, Any]:
    result = FabTwinSimulator(config, seed).generate()
    output.mkdir(parents=True, exist_ok=True)
    events_path = output / "events.json"
    truth_path = output / "ground_truth.json"
    data_card_path = output / "data-card.md"
    events_path.write_text(json.dumps(result.events, indent=2, sort_keys=True), encoding="utf-8")
    truth_path.write_text(json.dumps(result.ground_truth, indent=2, sort_keys=True), encoding="utf-8")
    data_card_path.write_text(_data_card(config, seed), encoding="utf-8")
    manifest = {
        "artifact_kind": "fabtwin-sim-trace",
        "seed": seed,
        "config": config.to_dict(),
        "config_version": config.version,
        "generator_version": GENERATOR_VERSION,
        "schema_version": SCHEMA_VERSION,
        "canonical_event_hash": canonical_hash(result.events),
        "canonical_ground_truth_hash": canonical_hash(result.ground_truth),
        "files": {
            "events.json": _sha256_file(events_path),
            "ground_truth.json": _sha256_file(truth_path),
            "data-card.md": _sha256_file(data_card_path),
        },
        "regenerate_command": "uv run python -m simulator.generate --manifest manifest.json --output regenerated",
    }
    manifest_path = output / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")
    return manifest


def config_from_manifest(path: Path) -> tuple[int, SimulatorConfig]:
    manifest = json.loads(path.read_text(encoding="utf-8"))
    return int(manifest["seed"]), SimulatorConfig.from_dict(manifest["config"])


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a deterministic FabTwin-Sim trace")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--profile", choices=("test", "portfolio"), default="test")
    parser.add_argument("--manifest", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    if args.manifest:
        seed, config = config_from_manifest(args.manifest)
    else:
        seed, config = args.seed, load_config(args.profile)
    manifest = write_artifacts(args.output, seed, config)
    print(manifest["canonical_event_hash"])


if __name__ == "__main__":
    main()

