from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable, Protocol


@dataclass(frozen=True)
class StoredEvent:
    event: dict[str, Any]
    delivery_status: str
    sequence: int


@dataclass(frozen=True)
class QuarantinedEvent:
    raw_event: dict[str, Any]
    reason: str


class EventRepositoryPort(Protocol):
    def reserve_event_id(self, event_id: str) -> bool: ...
    def append_event(self, event: dict[str, Any], delivery_status: str) -> StoredEvent: ...
    def all_events(self) -> list[StoredEvent]: ...
    def append_outbox(self, topic: str, payload: dict[str, Any]) -> None: ...
    def outbox(self) -> list[dict[str, Any]]: ...
    def set_checkpoint(self, consumer: str, sequence: int) -> None: ...
    def checkpoint(self, consumer: str) -> int: ...


class CaseRepositoryPort(Protocol):
    def upsert_case(self, case: dict[str, Any]) -> bool: ...
    def get_case(self, case_id: str) -> dict[str, Any] | None: ...
    def list_cases(self) -> list[dict[str, Any]]: ...
    def append_audit(self, record: dict[str, Any]) -> None: ...
    def audit_log(self) -> list[dict[str, Any]]: ...


class QuarantinePort(Protocol):
    def put(self, raw_event: dict[str, Any], reason: str) -> None: ...
    def all(self) -> list[QuarantinedEvent]: ...


class EventBusPort(Protocol):
    def publish(self, topic: str, event: dict[str, Any]) -> None: ...
    def subscribe(self, topic: str, handler: Callable[[dict[str, Any]], None]) -> None: ...

